"""Initial migration

Revision ID: 41dd87ab5454
Revises: 
Create Date: 2025-03-19 22:46:47.527654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dd87ab5454'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_received', sa.String(), nullable=False))
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('grades', 'date_received')
    # ### end Alembic commands ###
